# docker-compose.yml
version: '2'
services:

    py1-5:
        image: 8901310/exadel341:1.06g
        ports:
          - 1024-1028:80
        deploy:
          mode: replicated
          replicas: 5
        environment:
        - GREETING=hello1
        env_file:
        - .env

    java:
        depends_on:
            - db
        image: milkyway/java-hello-world:latest
        environment:
        - GREETING=hello6
        env_file:
        - .env

    db:
        depends_on:
            - py1-5
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_DATABASE: base
            МYSQL_USЕR: user
            MYSQL_PASSWORD: qwerty
        env_file:
        - .env
